[project]
name = "lerf"
version = "0.1.0"

[project.entry-points.'nerfstudio.method_configs']
lerf = 'lerf.lerf_config:lerf_method'
lerf_big = 'lerf.lerf_config:lerf_method_big'
lerf_lite = 'lerf.lerf_config:lerf_method_lite'
lerf_openai = 'lerf.lerf_config:lerf_openai_method'