defaults:
  - vanilla_nerf
  - _self_

method_name: instant_ngp
data.dataloader.num_rays_per_batch: 4096
data.val_num_rays_per_chunk: 16384

graph:
  network:
    _target_: radiance.nerf.graph.instant_ngp.NGPGraph
    field_implementation: torch # torch, tcnn, ...
    loss_coefficients: # loss coefficients
      rgb_loss: 1.0

  # optimizer options for network
  param_groups:
    fields:
      optimizer:
        lr: 1e-2