defaults:
  - default_setup
  - _self_

experiment_name: blender_lego
method_name: vanilla_nerf

graph:
  # saving model specifications
  model_dir: /tmp/radiance_models/
  steps_per_save: null
  steps_per_test: 100
  max_num_iterations: 1000000

  # pretrained loading options
  resume_train:
    load_dir: # pretrained model directory
    load_step: # pretrained model's step number

  network:
    _target_: radiance.nerf.graph.vanilla_nerf.NeRFGraph
    near_plane: 2.0
    far_plane: 6.0
    num_coarse_samples: 64
    num_importance_samples: 128

    loss_coefficients: # loss coefficients
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0

  # optimizer options for network
  param_groups:
    fields:
      optimizer:
        _target_: torch.optim.RAdam
        lr: 0.0005
      scheduler:
        _target_: radiance.nerf.optimizers.ExponentialDecaySchedule
        lr_final: 0.000005
        max_steps: 1000000
